"""MCP-aware Hermes client — replaces the legacy hermes_client.py.

Architecture
------------
1. The FastMCP ``dental_mcp`` server runs **in-process** (same Python process
   as FastAPI).  No extra port or subprocess is required.
2. ``fastmcp.Client(dental_mcp)`` communicates with the server over an
   in-memory transport — zero network overhead.
3. Tool schemas are auto-generated by FastMCP from the function signatures and
   docstrings defined in ``mcp_server.py``.
4. The OpenRouter API is called with those schemas; when the model requests a
   tool call the MCP client dispatches it and the result is fed back to the
   model for a final natural-language reply.

Return contract
---------------
``call_hermes()`` returns a dict with the **same shape** as the legacy
``hermes_client.call_hermes()`` so that ``main.py`` requires only a
one-line import change:

    {
        "success":       bool,
        "tool_name":     str | None,
        "tool_arguments": dict | None,
        "tool_result":   dict | None,
        "assistant_reply": str,
        "error":         str,      # only when success=False
    }
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any

import httpx
from fastmcp import Client
from mcp.types import TextContent

from config import settings
from mcp_server import dental_mcp

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _extract_text(content: Any) -> str:
    """Pull plain text out of an MCP CallToolResult or content list.

    fastmcp >= 3.x returns a CallToolResult object; older versions returned
    a plain list.  We handle both shapes here.
    """
    # CallToolResult object (fastmcp 3.4.x) — iterate its .content list
    if hasattr(content, "content"):
        content = content.content

    # If we got a structured_content / data dict directly, serialise it
    if isinstance(content, dict):
        return json.dumps(content)

    # Iterable of content items (TextContent etc.)
    if hasattr(content, "__iter__") and not isinstance(content, str):
        parts: list[str] = []
        for item in content:
            if isinstance(item, TextContent):
                parts.append(item.text)
            elif hasattr(item, "text"):
                parts.append(str(item.text))
            else:
                parts.append(str(item))
        return "\n".join(parts)

    return str(content)


async def _get_mcp_tool_schemas() -> list[dict]:
    """Return OpenRouter-compatible tool schema list from the MCP server."""
    async with Client(dental_mcp) as mcp_client:
        mcp_tools = await mcp_client.list_tools()

    openrouter_tools: list[dict] = []
    for t in mcp_tools:
        # FastMCP exposes inputSchema as a dict (JSON Schema object)
        input_schema = t.inputSchema if hasattr(t, "inputSchema") else {}
        if hasattr(input_schema, "model_dump"):
            input_schema = input_schema.model_dump(exclude_none=True)

        openrouter_tools.append(
            {
                "type": "function",
                "function": {
                    "name": t.name,
                    "description": t.description or "",
                    "parameters": input_schema,
                },
            }
        )
    return openrouter_tools


async def _dispatch_tool_via_mcp(tool_name: str, tool_args: dict) -> dict:
    """Execute a tool through the MCP server and return a plain dict result."""
    async with Client(dental_mcp) as mcp_client:
        result = await mcp_client.call_tool(tool_name, tool_args)

    # fastmcp 3.x: prefer the structured_content / data dict if available
    if hasattr(result, "data") and isinstance(result.data, dict):
        return result.data
    if hasattr(result, "structured_content") and isinstance(result.structured_content, dict):
        return result.structured_content

    # Fallback: extract text and try JSON-parse
    raw_text = _extract_text(result)
    try:
        return json.loads(raw_text)
    except (json.JSONDecodeError, TypeError):
        return {"result": raw_text}


# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "You are a professional dental clinic assistant powered by the Hermes MCP Agent Framework. "
    "You help patients book, reschedule, and cancel dental appointments, and answer frequently "
    "asked questions about dental care, office hours, insurance, and costs. "
    "Always be polite, concise, and confirm details before taking actions. "
    "Use the available tools whenever needed to fulfil the patient's request."
)

# ---------------------------------------------------------------------------
# Core async implementation
# ---------------------------------------------------------------------------

async def _call_hermes_async(user_message: str, context: list) -> dict:
    """Async implementation of the MCP-aware Hermes chat pipeline."""

    if not settings.OPENROUTER_API_KEY:
        return {"success": False, "error": "OPENROUTER_API_KEY not set in .env"}
    if not settings.OPENROUTER_MODEL:
        return {"success": False, "error": "OPENROUTER_MODEL not set in .env"}

    # ------------------------------------------------------------------
    # 1. Get tool schemas from the MCP server
    # ------------------------------------------------------------------
    try:
        tools_payload = await _get_mcp_tool_schemas()
    except Exception as exc:
        logger.error("Failed to load MCP tool schemas: %s", exc)
        return {"success": False, "error": f"MCP tool schema error: {exc}"}

    # ------------------------------------------------------------------
    # 2. Build message history
    # ------------------------------------------------------------------
    messages: list[dict] = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.extend(context)
    messages.append({"role": "user", "content": user_message})

    api_url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {settings.OPENROUTER_API_KEY}",
        "Referer": "http://localhost:3000",
        "X-Title": "Dental Web Agent (MCP)",
        "Content-Type": "application/json",
    }

    # ------------------------------------------------------------------
    # 3. First OpenRouter call — model may request a tool call
    # ------------------------------------------------------------------
    first_payload = {
        "model": settings.OPENROUTER_MODEL,
        "messages": messages,
        "tools": tools_payload,
        "tool_choice": "auto",
        "temperature": 0.7,
        "max_tokens": 1024,
    }

    try:
        async with httpx.AsyncClient(timeout=30.0) as http:
            resp = await http.post(api_url, json=first_payload, headers=headers)
    except httpx.HTTPError as exc:
        return {"success": False, "error": f"API request failed: {exc}"}

    if resp.status_code >= 400:
        return {
            "success": False,
            "error": f"OpenRouter returned {resp.status_code}: {resp.text}",
        }

    try:
        data = resp.json()
        choice = data["choices"][0]
        message = choice.get("message", {})
    except (KeyError, IndexError, json.JSONDecodeError) as exc:
        return {"success": False, "error": f"Failed to parse response: {exc}"}

    # ------------------------------------------------------------------
    # 4. Handle tool call (OpenRouter-style tool_calls array)
    # ------------------------------------------------------------------
    tool_calls = message.get("tool_calls") or []
    if tool_calls:
        tool_call = tool_calls[0]
        tool_name = tool_call.get("function", {}).get("name")
        raw_args = tool_call.get("function", {}).get("arguments", "{}")
        try:
            tool_args = json.loads(raw_args)
        except json.JSONDecodeError:
            tool_args = {}

        # Dispatch via MCP
        try:
            tool_result = await _dispatch_tool_via_mcp(tool_name, tool_args)
        except Exception as exc:
            logger.error("MCP tool dispatch error for %s: %s", tool_name, exc)
            tool_result = {"error": str(exc)}

        # Append assistant + tool messages and re-call for final reply
        assistant_content = message.get("content") or ""
        messages.append({
            "role": "assistant",
            "content": assistant_content,
            "tool_calls": tool_calls,
        })
        messages.append({
            "role": "tool",
            "tool_call_id": tool_call.get("id"),
            "content": json.dumps(tool_result),
        })

        second_payload = {
            "model": settings.OPENROUTER_MODEL,
            "messages": messages,
            "temperature": 0.7,
            "max_tokens": 1024,
            # No tools on the second call so the model always produces text
        }

        try:
            async with httpx.AsyncClient(timeout=30.0) as http:
                resp2 = await http.post(api_url, json=second_payload, headers=headers)
        except httpx.HTTPError as exc:
            return {"success": False, "error": f"Second API call failed: {exc}"}

        if resp2.status_code >= 400:
            return {
                "success": False,
                "error": f"OpenRouter (2nd call) returned {resp2.status_code}: {resp2.text}",
            }

        try:
            final_data = resp2.json()
            final_message = (
                final_data["choices"][0].get("message", {}).get("content", "")
            )
        except (KeyError, IndexError, json.JSONDecodeError) as exc:
            return {"success": False, "error": f"Failed to parse final response: {exc}"}

        return {
            "success": True,
            "tool_name": tool_name,
            "tool_arguments": tool_args,
            "tool_result": tool_result,
            "assistant_reply": final_message,
        }

    # ------------------------------------------------------------------
    # 5. Handle legacy OpenAI-style function_call (fallback)
    # ------------------------------------------------------------------
    function_call = message.get("function_call")
    if function_call:
        tool_name = function_call.get("name")
        try:
            tool_args = json.loads(function_call.get("arguments") or "{}")
        except json.JSONDecodeError:
            tool_args = {}

        try:
            tool_result = await _dispatch_tool_via_mcp(tool_name, tool_args)
        except Exception as exc:
            tool_result = {"error": str(exc)}

        assistant_content = message.get("content") or ""
        messages.append({"role": "assistant", "content": assistant_content})
        messages.append({
            "role": "function",
            "name": tool_name,
            "content": json.dumps(tool_result),
        })

        second_payload = {
            "model": settings.OPENROUTER_MODEL,
            "messages": messages,
            "temperature": 0.7,
            "max_tokens": 1024,
        }

        try:
            async with httpx.AsyncClient(timeout=30.0) as http:
                resp2 = await http.post(api_url, json=second_payload, headers=headers)
        except httpx.HTTPError as exc:
            return {"success": False, "error": f"Second API call failed: {exc}"}

        if resp2.status_code >= 400:
            return {
                "success": False,
                "error": f"OpenRouter (2nd call) returned {resp2.status_code}: {resp2.text}",
            }

        try:
            final_data = resp2.json()
            final_message = (
                final_data["choices"][0].get("message", {}).get("content", "")
            )
        except (KeyError, IndexError, json.JSONDecodeError) as exc:
            return {"success": False, "error": f"Failed to parse final response: {exc}"}

        return {
            "success": True,
            "tool_name": tool_name,
            "tool_arguments": tool_args,
            "tool_result": tool_result,
            "assistant_reply": final_message,
        }

    # ------------------------------------------------------------------
    # 6. No tool call — plain conversational reply
    # ------------------------------------------------------------------
    return {
        "success": True,
        "tool_name": None,
        "tool_arguments": None,
        "tool_result": None,
        "assistant_reply": message.get("content") or "No response from assistant.",
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def call_hermes(user_message: str, context: list = None) -> dict:
    """MCP-aware async replacement for the legacy ``hermes_client.call_hermes``.

    This is a native coroutine — use ``await call_hermes(...)`` from FastAPI
    async endpoints.  For sync callers (tests, scripts) use::

        import asyncio
        result = asyncio.run(call_hermes(message))

    Args:
        user_message: The patient's chat input.
        context:      Optional prior message list for multi-turn conversation.

    Returns:
        dict with keys: success, tool_name, tool_arguments, tool_result,
        assistant_reply (and error when success=False).
    """
    ctx = list(context) if context else []
    return await _call_hermes_async(user_message, ctx)
